## Identities point clouds analysis

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pickle
import plotly.graph_objects as go

MODEL_NAMES = ["retina_facenet","retina_arcface"]

Load the results

In [3]:
dataset = "CelebA"
nrep = 30

with open(f'../results/{dataset}_PHdim_barycenters_nrep{nrep}.pickle', 'rb') as handle:
        dimensions = pickle.load(handle)


In [11]:
for m, model_name in enumerate(MODEL_NAMES):
    fig = go.Figure()
    fig.add_trace(go.Histogram(x=np.array(dimensions[m]), name = model_name))
    fig.update_layout(barmode='overlay',width=800,height = 200, title = model_name,margin=dict(l=30,r=1,b=1,t=35))
    fig.update_traces(opacity=0.5)
    fig.show()

In [13]:
dimensions[1]

[array([30.63201535, 29.7139144 , 32.97640286, 31.20316223]),
 array([31.76415383, 35.83213374, 31.88608947, 32.88153121]),
 array([32.26252085, 33.24626027, 34.19581132, 30.99214953]),
 array([33.24193424, 32.55277687, 32.56710653, 30.47616428]),
 array([28.80011337, 30.55762779, 31.76527463, 31.93169269]),
 array([34.54237709, 32.52333468, 32.67531324, 32.71766832]),
 array([32.52118465, 33.44950442, 29.83734136, 30.29313504]),
 array([34.80972383, 34.8567766 , 35.56010844, 31.56978799]),
 array([29.93836328, 31.21734524, 33.64667001, 32.70834969]),
 array([36.06432183, 31.59090864, 32.82024216, 33.49372882]),
 array([31.62872593, 29.92104324, 30.90730211, 31.58358865]),
 array([32.18654443, 31.59355345, 32.66541515, 32.34013838]),
 array([31.67364187, 30.29537975, 35.61835305, 31.92965889]),
 array([32.49351784, 32.14970618, 30.79752737, 31.25551419]),
 array([31.49223374, 33.81137938, 33.22740868, 31.32293886]),
 array([31.01647619, 33.06709838, 29.35036278, 33.02386757]),
 array([